######################################################################
# Automatically generated by qmake (3.0) ? 1? 27 15:19:40 2017
######################################################################

TEMPLATE = app
TARGET = cpi2
CONFIG += console c++11
QT     -= gui
INCLUDEPATH += .

# Input
SOURCES += main.cpp

isEmpty(target.path) {
  windows {
    target.path = .
  } else:macx {
    target.path = /usr/local/bin
  } else:unix {
    target.path = /usr/bin
  }
}
INSTALLS += target
