name: ActionsCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Homebrew
        run: |
          brew install qt6 openblas pkg-config llvm
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
      - name: build
        run: |
          qmake CONFIG+=release
          make
      - name: tests
        env:
          PKG_CONFIG_PATH: /opt/homebrew/opt/openblas/lib/pkgconfig
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true


  ci-ubuntu24-qt6-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends g++ make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          qmake6 CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/ranges.cpp
          ./cpi tests/concept_add.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu24-qt6-clang:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt purge -y gcc g++
          sudo apt-get install -y --no-install-recommends clang make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          qmake6 -spec linux-clang CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu22-qt6-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends g++ make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          qmake6 CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/ranges.cpp
          ./cpi tests/concept_add.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu22-qt6-clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt-get update -qq
          sudo apt purge -y gcc g++
          sudo apt-get install -y --no-install-recommends clang make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          qmake6 -spec linux-clang CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  # ci-ubuntu20-qt5-gcc:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: apt
  #       run: |
  #         sudo apt-get update -qq
  #         sudo apt-get install -y --no-install-recommends g++ make qtbase5-dev qt5-default qt5-qmake
  #     - name: build
  #       run: |
  #         qmake CONFIG+=release
  #         make
  #     - name: tests
  #       run: |
  #         ./cpi tests/helloworld.cpp
  #         ./cpi tests/sqrt.cpp 7
  #         ./cpi tests/fibonacci.cpp 10
  #         ./cpi tests/unique_ptr.cpp
  #     - name: error tests
  #       run: |
  #         ./cpi tests/error_code.cpp
  #       continue-on-error: true

  # ci-ubuntu20-qt5-clang:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: apt
  #       run: |
  #         sudo apt-get update -qq
  #         sudo apt purge -y gcc g++
  #         sudo apt-get install -y --no-install-recommends clang make qtbase5-dev qt5-default qt5-qmake
  #     - name: build
  #       run: |
  #         qmake -spec linux-clang CONFIG+=release
  #         make
  #     - name: tests
  #       run: |
  #         ./cpi tests/helloworld.cpp
  #         ./cpi tests/sqrt.cpp 7
  #         ./cpi tests/fibonacci.cpp 10
  #         ./cpi tests/unique_ptr.cpp
  #     - name: error tests
  #       run: |
  #         ./cpi tests/error_code.cpp
  #       continue-on-error: true

  ci-windows-qt68-msvc2022:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          arch:         win64_msvc2022_64
          setup-python: false
      - name: Checkout msbuild
        id: checkout_msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17,18)'  # 17.xx
          msbuild-architecture: x64
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set CL=/MP
          qmake CONFIG+=release
          nmake
      - name: tests
        shell: cmd
        run: |
          cpi.bat tests\helloworld.cpp
          cpi.bat tests\sqrt.cpp 7
          cpi.bat tests\fibonacci.cpp 10
          cpi.bat tests\unique_ptr.cpp
          cpi.bat tests\optional.cpp
          cpi.bat tests\if_initializer.cpp
          cpi.bat tests\ranges.cpp
          cpi.bat tests\concept_add.cpp
          cpi.bat tests\u8hello.cpp
      - name: error tests
        shell: cmd
        run: |
          cpi.bat tests\error_code.cpp
        continue-on-error: true

  ci-windows-qt68-msvc2019:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          setup-python: false
      - name: Install VisualStudio tools
        run: |
          choco install visualstudio2019community -y --no-progress
          choco install visualstudio2019-workload-nativedesktop -y --no-progress
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
          set CL=/MP
          qmake CONFIG+=release
          nmake
      - name: tests
        shell: cmd
        run: |
          cpi.bat tests\helloworld.cpp
          cpi.bat tests\sqrt.cpp 7
          cpi.bat tests\fibonacci.cpp 10
          cpi.bat tests\unique_ptr.cpp
          cpi.bat tests\optional.cpp
          cpi.bat tests\if_initializer.cpp
          cpi.bat tests\ranges.cpp
          cpi.bat tests\concept_add.cpp
          cpi.bat tests\u8hello.cpp
      - name: error tests
        shell: cmd
        run: |
          cpi.bat tests\error_code.cpp
        continue-on-error: true
