name: ActionsCI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci-macos26:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@main
      - name: Homebrew
        run: |
          brew install qt6 openblas pkg-config
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
      - name: build
        run: |
          clang++ --version
          qmake CONFIG+=release
          make
      - name: tests
        env:
          PKG_CONFIG_PATH: /opt/homebrew/opt/openblas/lib/pkgconfig
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          # ./cpi tests/fibonacci_coroutine.cpp 50
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-macos15:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@main
      - name: Homebrew
        run: |
          brew install qt6 openblas pkg-config
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
      - name: build
        run: |
          clang++ --version
          qmake CONFIG+=release
          make
      - name: tests
        env:
          PKG_CONFIG_PATH: /opt/homebrew/opt/openblas/lib/pkgconfig
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          # ./cpi tests/fibonacci_coroutine.cpp 50
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu26-gcc:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends g++ make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          g++ --version
          qmake6 CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/fibonacci_coroutine.cpp 50
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/ranges.cpp
          ./cpi tests/concept_add.cpp
          ./cpi tests/dgemm.cpp
          ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu26-clang:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends clang make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          clang++ --version
          qmake6 -spec linux-clang CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          ./cpi tests/fibonacci_coroutine.cpp 50
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/dgemm.cpp
          ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-ubuntu24:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: apt
        run: |
          sudo apt update -qq
          sudo apt install -y --no-install-recommends g++ make qmake6 qt6-base-dev qt6-base-dev-tools libopenblas-dev pkg-config
      - name: build
        run: |
          g++ --version
          qmake6 CONFIG+=release
          make
      - name: tests
        run: |
          ./cpi tests/helloworld.cpp
          ./cpi tests/sqrt.cpp 7
          ./cpi tests/fibonacci.cpp 10
          # ./cpi tests/fibonacci_coroutine.cpp 50
          ./cpi tests/unique_ptr.cpp
          ./cpi tests/optional.cpp
          ./cpi tests/if_initializer.cpp
          ./cpi tests/ranges.cpp
          ./cpi tests/concept_add.cpp
          ./cpi tests/dgemm.cpp
          # ./cpi tests/u8hello.cpp
      - name: error tests
        run: |
          ./cpi tests/error_code.cpp
        continue-on-error: true

  ci-windows-qt68-vs2026:
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          setup-python: false
      # - name: Checkout msbuild
      #   id: checkout_msbuild
      #   uses: microsoft/setup-msbuild@v3
      #   with:
      #     vs-version: '[18,19)'  # 18.xx
      #     msbuild-architecture: x64
      - name: Build
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -find **\vcvarsall.bat
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set CL=/MP
          qmake CONFIG+=release
          nmake
      - name: tests
        shell: cmd
        run: |
          cpi.bat tests\helloworld.cpp
          cpi.bat tests\sqrt.cpp 7
          cpi.bat tests\fibonacci.cpp 10
          cpi.bat tests\fibonacci_coroutine.cpp 50
          cpi.bat tests\unique_ptr.cpp
          cpi.bat tests\optional.cpp
          cpi.bat tests\if_initializer.cpp
          cpi.bat tests\ranges.cpp
          cpi.bat tests\concept_add.cpp
          cpi.bat tests\u8hello.cpp
      - name: error tests
        shell: cmd
        run: |
          cpi.bat tests\error_code.cpp
        continue-on-error: true

  ci-windows-qt68-vs2022:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          setup-python: false
      - name: Checkout msbuild
        id: checkout_msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17,18)'  # 17.xx
          msbuild-architecture: x64
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set CL=/MP
          qmake CONFIG+=release
          nmake
      - name: tests
        shell: cmd
        run: |
          cpi.bat tests\helloworld.cpp
          cpi.bat tests\sqrt.cpp 7
          cpi.bat tests\fibonacci.cpp 10
          cpi.bat tests\fibonacci_coroutine.cpp 50
          cpi.bat tests\unique_ptr.cpp
          cpi.bat tests\optional.cpp
          cpi.bat tests\if_initializer.cpp
          cpi.bat tests\ranges.cpp
          cpi.bat tests\concept_add.cpp
          cpi.bat tests\u8hello.cpp
      - name: error tests
        shell: cmd
        run: |
          cpi.bat tests\error_code.cpp
        continue-on-error: true

  ci-windows-qt68-vs2019:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          setup-python: false
      - name: Install VisualStudio tools
        run: |
          choco install visualstudio2019community -y --no-progress
          choco install visualstudio2019-workload-nativedesktop -y --no-progress
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
          set CL=/MP
          qmake CONFIG+=release
          nmake
      - name: tests
        shell: cmd
        run: |
          cpi.bat tests\helloworld.cpp
          cpi.bat tests\sqrt.cpp 7
          cpi.bat tests\fibonacci.cpp 10
          cpi.bat tests\fibonacci_coroutine.cpp 50
          cpi.bat tests\unique_ptr.cpp
          cpi.bat tests\optional.cpp
          cpi.bat tests\if_initializer.cpp
          cpi.bat tests\ranges.cpp
          cpi.bat tests\concept_add.cpp
          cpi.bat tests\u8hello.cpp
      - name: error tests
        shell: cmd
        run: |
          cpi.bat tests\error_code.cpp
        continue-on-error: true
