name: Build and Release

on:
  push:
    tags:
      - 'v*'

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      6.8
          host:         windows
          target:       desktop
          setup-python: false

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          # where.exe qmake
          # where.exe cl.exe
          # where.exe nmake.exe
          qmake CONFIG+=release
          nmake

      - name: Create 7Z file
        run: |
          7z a cpi-windows.7z  cpi.exe cpi.bat Qt6Core.dll LICENSE translations

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" --title "Cpi version ${GITHUB_REF_NAME} release" --draft --prerelease

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF_NAME}" "cpi-windows.7z#cpi-${GITHUB_REF_NAME}-windows.7z" --clobber
